-- GENERATED FILE — do not edit.
-- Source: data/muscle-groups.ts, data/exercises.seed.ts, data/badges.config.ts
-- Regenerate: npm run seed:gen
--
-- Idempotent: every statement upserts on a stable key, so re-running after
-- an edit updates rows in place rather than duplicating the library.

begin;

-- Muscle groups
insert into hadid.muscle_groups (id, name, region, body_side, svg_group, sort_order) values
  ('chest', 'Chest', 'upper', 'front', 'chest', 1),
  ('front_delts', 'Front Delts', 'upper', 'front', 'front-delts', 2),
  ('biceps', 'Biceps', 'upper', 'front', 'biceps', 3),
  ('lats', 'Lats', 'upper', 'back', 'lats', 4),
  ('traps', 'Traps', 'upper', 'back', 'traps', 5),
  ('rhomboids', 'Rhomboids', 'upper', 'back', 'rhomboids', 6),
  ('rear_delts', 'Rear Delts', 'upper', 'back', 'rear-delts', 7),
  ('triceps', 'Triceps', 'upper', 'back', 'triceps', 8),
  ('side_delts', 'Side Delts', 'upper', 'both', 'side-delts', 9),
  ('forearms', 'Forearms', 'upper', 'both', 'forearms', 10),
  ('abs', 'Abs', 'core', 'front', 'abs', 11),
  ('obliques', 'Obliques', 'core', 'front', 'obliques', 12),
  ('lower_back', 'Lower Back', 'core', 'back', 'lower-back', 13),
  ('quads', 'Quads', 'lower', 'front', 'quads', 14),
  ('hamstrings', 'Hamstrings', 'lower', 'back', 'hamstrings', 15),
  ('glutes', 'Glutes', 'lower', 'back', 'glutes', 16),
  ('calves', 'Calves', 'lower', 'both', 'calves', 17),
  ('adductors', 'Adductors', 'lower', 'front', 'adductors', 18)
on conflict (id) do update set
  name = excluded.name, region = excluded.region,
  body_side = excluded.body_side, svg_group = excluded.svg_group,
  sort_order = excluded.sort_order;

-- Built-in exercises. user_id stays null: these belong to nobody.
insert into hadid.exercises (slug, name, aliases, equipment, type, is_unilateral) values
  ('barbell-bench-press', 'Barbell Bench Press', array['bench', 'bench press', 'bp']::text[], 'barbell', 'strength', false),
  ('incline-barbell-bench-press', 'Incline Barbell Bench Press', array['incline bench']::text[], 'barbell', 'strength', false),
  ('decline-barbell-bench-press', 'Decline Barbell Bench Press', array['decline bench']::text[], 'barbell', 'strength', false),
  ('dumbbell-bench-press', 'Dumbbell Bench Press', array['db bench']::text[], 'dumbbell', 'strength', false),
  ('incline-dumbbell-press', 'Incline Dumbbell Press', array['incline db press']::text[], 'dumbbell', 'strength', false),
  ('decline-dumbbell-press', 'Decline Dumbbell Press', '{}'::text[], 'dumbbell', 'strength', false),
  ('dumbbell-fly', 'Dumbbell Fly', array['flye', 'chest fly']::text[], 'dumbbell', 'strength', false),
  ('incline-dumbbell-fly', 'Incline Dumbbell Fly', '{}'::text[], 'dumbbell', 'strength', false),
  ('cable-fly', 'Cable Fly', array['cable flye']::text[], 'cable', 'strength', false),
  ('cable-crossover', 'Cable Crossover', '{}'::text[], 'cable', 'strength', false),
  ('machine-chest-press', 'Machine Chest Press', '{}'::text[], 'machine', 'strength', false),
  ('pec-deck', 'Pec Deck', array['machine fly']::text[], 'machine', 'strength', false),
  ('push-up', 'Push-Up', array['pushup', 'press up']::text[], 'bodyweight', 'strength', false),
  ('chest-dip', 'Chest Dip', array['dips']::text[], 'bodyweight', 'strength', false),
  ('deadlift', 'Deadlift', array['conventional deadlift', 'dl']::text[], 'barbell', 'strength', false),
  ('sumo-deadlift', 'Sumo Deadlift', '{}'::text[], 'barbell', 'strength', false),
  ('rack-pull', 'Rack Pull', '{}'::text[], 'barbell', 'strength', false),
  ('barbell-row', 'Barbell Row', array['bent over row', 'bor']::text[], 'barbell', 'strength', false),
  ('pendlay-row', 'Pendlay Row', '{}'::text[], 'barbell', 'strength', false),
  ('dumbbell-row', 'Dumbbell Row', array['one arm row', 'db row']::text[], 'dumbbell', 'strength', true),
  ('t-bar-row', 'T-Bar Row', '{}'::text[], 'barbell', 'strength', false),
  ('chest-supported-row', 'Chest-Supported Row', '{}'::text[], 'machine', 'strength', false),
  ('seated-cable-row', 'Seated Cable Row', array['cable row']::text[], 'cable', 'strength', false),
  ('machine-row', 'Machine Row', '{}'::text[], 'machine', 'strength', false),
  ('lat-pulldown', 'Lat Pulldown', array['pulldown']::text[], 'cable', 'strength', false),
  ('close-grip-lat-pulldown', 'Close-Grip Lat Pulldown', '{}'::text[], 'cable', 'strength', false),
  ('pull-up', 'Pull-Up', array['pullup']::text[], 'bodyweight', 'strength', false),
  ('chin-up', 'Chin-Up', array['chinup']::text[], 'bodyweight', 'strength', false),
  ('straight-arm-pulldown', 'Straight-Arm Pulldown', '{}'::text[], 'cable', 'strength', false),
  ('barbell-shrug', 'Barbell Shrug', array['shrug']::text[], 'barbell', 'strength', false),
  ('dumbbell-shrug', 'Dumbbell Shrug', '{}'::text[], 'dumbbell', 'strength', false),
  ('face-pull', 'Face Pull', '{}'::text[], 'cable', 'strength', false),
  ('back-extension', 'Back Extension', array['hyperextension']::text[], 'bodyweight', 'strength', false),
  ('overhead-press', 'Overhead Press', array['ohp', 'military press', 'shoulder press']::text[], 'barbell', 'strength', false),
  ('seated-dumbbell-shoulder-press', 'Seated Dumbbell Shoulder Press', array['db shoulder press']::text[], 'dumbbell', 'strength', false),
  ('arnold-press', 'Arnold Press', '{}'::text[], 'dumbbell', 'strength', false),
  ('machine-shoulder-press', 'Machine Shoulder Press', '{}'::text[], 'machine', 'strength', false),
  ('push-press', 'Push Press', '{}'::text[], 'barbell', 'strength', false),
  ('lateral-raise', 'Lateral Raise', array['side raise', 'lat raise']::text[], 'dumbbell', 'strength', false),
  ('cable-lateral-raise', 'Cable Lateral Raise', '{}'::text[], 'cable', 'strength', true),
  ('front-raise', 'Front Raise', '{}'::text[], 'dumbbell', 'strength', false),
  ('rear-delt-fly', 'Rear Delt Fly', array['reverse fly']::text[], 'dumbbell', 'strength', false),
  ('reverse-pec-deck', 'Reverse Pec Deck', '{}'::text[], 'machine', 'strength', false),
  ('upright-row', 'Upright Row', '{}'::text[], 'barbell', 'strength', false),
  ('barbell-curl', 'Barbell Curl', array['bicep curl']::text[], 'barbell', 'strength', false),
  ('ez-bar-curl', 'EZ-Bar Curl', '{}'::text[], 'barbell', 'strength', false),
  ('dumbbell-curl', 'Dumbbell Curl', array['db curl']::text[], 'dumbbell', 'strength', false),
  ('hammer-curl', 'Hammer Curl', '{}'::text[], 'dumbbell', 'strength', false),
  ('incline-dumbbell-curl', 'Incline Dumbbell Curl', '{}'::text[], 'dumbbell', 'strength', false),
  ('preacher-curl', 'Preacher Curl', '{}'::text[], 'barbell', 'strength', false),
  ('concentration-curl', 'Concentration Curl', '{}'::text[], 'dumbbell', 'strength', true),
  ('cable-curl', 'Cable Curl', '{}'::text[], 'cable', 'strength', false),
  ('spider-curl', 'Spider Curl', '{}'::text[], 'dumbbell', 'strength', false),
  ('close-grip-bench-press', 'Close-Grip Bench Press', array['cgbp']::text[], 'barbell', 'strength', false),
  ('skullcrusher', 'Skullcrusher', array['lying tricep extension']::text[], 'barbell', 'strength', false),
  ('overhead-tricep-extension', 'Overhead Tricep Extension', '{}'::text[], 'dumbbell', 'strength', false),
  ('tricep-pushdown', 'Tricep Pushdown', array['pushdown']::text[], 'cable', 'strength', false),
  ('rope-pushdown', 'Rope Pushdown', '{}'::text[], 'cable', 'strength', false),
  ('tricep-kickback', 'Tricep Kickback', '{}'::text[], 'dumbbell', 'strength', true),
  ('bench-dip', 'Bench Dip', '{}'::text[], 'bodyweight', 'strength', false),
  ('tricep-dip', 'Tricep Dip', '{}'::text[], 'bodyweight', 'strength', false),
  ('diamond-push-up', 'Diamond Push-Up', '{}'::text[], 'bodyweight', 'strength', false),
  ('wrist-curl', 'Wrist Curl', '{}'::text[], 'dumbbell', 'strength', false),
  ('reverse-wrist-curl', 'Reverse Wrist Curl', '{}'::text[], 'dumbbell', 'strength', false),
  ('farmers-walk', 'Farmer''s Walk', array['farmers carry']::text[], 'dumbbell', 'strength', false),
  ('reverse-curl', 'Reverse Curl', '{}'::text[], 'barbell', 'strength', false),
  ('back-squat', 'Back Squat', array['squat']::text[], 'barbell', 'strength', false),
  ('front-squat', 'Front Squat', '{}'::text[], 'barbell', 'strength', false),
  ('goblet-squat', 'Goblet Squat', '{}'::text[], 'dumbbell', 'strength', false),
  ('hack-squat', 'Hack Squat', '{}'::text[], 'machine', 'strength', false),
  ('leg-press', 'Leg Press', '{}'::text[], 'machine', 'strength', false),
  ('bulgarian-split-squat', 'Bulgarian Split Squat', array['bss', 'rear foot elevated split squat']::text[], 'dumbbell', 'strength', true),
  ('walking-lunge', 'Walking Lunge', array['lunge']::text[], 'dumbbell', 'strength', true),
  ('reverse-lunge', 'Reverse Lunge', '{}'::text[], 'dumbbell', 'strength', true),
  ('step-up', 'Step-Up', '{}'::text[], 'dumbbell', 'strength', true),
  ('romanian-deadlift', 'Romanian Deadlift', array['rdl']::text[], 'barbell', 'strength', false),
  ('stiff-leg-deadlift', 'Stiff-Leg Deadlift', '{}'::text[], 'barbell', 'strength', false),
  ('good-morning', 'Good Morning', '{}'::text[], 'barbell', 'strength', false),
  ('leg-extension', 'Leg Extension', '{}'::text[], 'machine', 'strength', false),
  ('lying-leg-curl', 'Lying Leg Curl', array['hamstring curl']::text[], 'machine', 'strength', false),
  ('seated-leg-curl', 'Seated Leg Curl', '{}'::text[], 'machine', 'strength', false),
  ('nordic-curl', 'Nordic Curl', '{}'::text[], 'bodyweight', 'strength', false),
  ('hip-thrust', 'Hip Thrust', '{}'::text[], 'barbell', 'strength', false),
  ('glute-bridge', 'Glute Bridge', '{}'::text[], 'bodyweight', 'strength', false),
  ('cable-kickback', 'Cable Kickback', '{}'::text[], 'cable', 'strength', true),
  ('standing-calf-raise', 'Standing Calf Raise', array['calf raise']::text[], 'machine', 'strength', false),
  ('seated-calf-raise', 'Seated Calf Raise', '{}'::text[], 'machine', 'strength', false),
  ('adductor-machine', 'Adductor Machine', array['hip adduction']::text[], 'machine', 'strength', false),
  ('abductor-machine', 'Abductor Machine', array['hip abduction']::text[], 'machine', 'strength', false),
  ('plank', 'Plank', '{}'::text[], 'bodyweight', 'strength', false),
  ('side-plank', 'Side Plank', '{}'::text[], 'bodyweight', 'strength', true),
  ('hanging-leg-raise', 'Hanging Leg Raise', '{}'::text[], 'bodyweight', 'strength', false),
  ('hanging-knee-raise', 'Hanging Knee Raise', '{}'::text[], 'bodyweight', 'strength', false),
  ('cable-crunch', 'Cable Crunch', '{}'::text[], 'cable', 'strength', false),
  ('crunch', 'Crunch', '{}'::text[], 'bodyweight', 'strength', false),
  ('sit-up', 'Sit-Up', '{}'::text[], 'bodyweight', 'strength', false),
  ('russian-twist', 'Russian Twist', '{}'::text[], 'bodyweight', 'strength', false),
  ('ab-wheel-rollout', 'Ab Wheel Rollout', '{}'::text[], 'other', 'strength', false),
  ('dead-bug', 'Dead Bug', '{}'::text[], 'bodyweight', 'strength', false),
  ('mountain-climber', 'Mountain Climber', '{}'::text[], 'bodyweight', 'strength', false),
  ('pallof-press', 'Pallof Press', '{}'::text[], 'cable', 'strength', true),
  ('treadmill-run', 'Treadmill Run', array['running', 'run']::text[], 'machine', 'cardio', false),
  ('stationary-bike', 'Stationary Bike', array['cycling', 'bike']::text[], 'machine', 'cardio', false),
  ('rowing-machine', 'Rowing Machine', array['erg', 'rower']::text[], 'machine', 'cardio', false),
  ('elliptical', 'Elliptical', '{}'::text[], 'machine', 'cardio', false),
  ('stair-climber', 'Stair Climber', '{}'::text[], 'machine', 'cardio', false),
  ('jump-rope', 'Jump Rope', array['skipping']::text[], 'other', 'cardio', false),
  ('arm-circles', 'Arm Circles', '{}'::text[], 'bodyweight', 'mobility', false),
  ('band-pass-through', 'Band Pass-Through', '{}'::text[], 'band', 'mobility', false),
  ('scapular-wall-slide', 'Scapular Wall Slide', '{}'::text[], 'bodyweight', 'mobility', false),
  ('cat-cow', 'Cat-Cow', '{}'::text[], 'bodyweight', 'mobility', false),
  ('worlds-greatest-stretch', 'World''s Greatest Stretch', '{}'::text[], 'bodyweight', 'mobility', true),
  ('hip-flexor-stretch', 'Hip Flexor Stretch', '{}'::text[], 'bodyweight', 'mobility', true),
  ('thoracic-rotation', 'Thoracic Rotation', '{}'::text[], 'bodyweight', 'mobility', true),
  ('leg-swing', 'Leg Swing', '{}'::text[], 'bodyweight', 'mobility', true)
on conflict (slug) do update set
  name = excluded.name, aliases = excluded.aliases,
  equipment = excluded.equipment, type = excluded.type,
  is_unilateral = excluded.is_unilateral;

-- Mappings are replaced wholesale rather than upserted, so a muscle removed
-- from an exercise in the source file is actually removed here.
delete from hadid.exercise_muscles em
using hadid.exercises e
where e.id = em.exercise_id and e.slug is not null;

insert into hadid.exercise_muscles (exercise_id, muscle_group_id, role, activation)
select e.id, v.muscle_group_id, v.role, v.activation
from (values
  ('barbell-bench-press', 'chest', 'primary', 1.00),
  ('barbell-bench-press', 'front_delts', 'secondary', 0.50),
  ('barbell-bench-press', 'triceps', 'secondary', 0.50),
  ('incline-barbell-bench-press', 'chest', 'primary', 0.90),
  ('incline-barbell-bench-press', 'front_delts', 'secondary', 0.60),
  ('incline-barbell-bench-press', 'triceps', 'secondary', 0.40),
  ('decline-barbell-bench-press', 'chest', 'primary', 0.90),
  ('decline-barbell-bench-press', 'triceps', 'secondary', 0.50),
  ('dumbbell-bench-press', 'chest', 'primary', 1.00),
  ('dumbbell-bench-press', 'front_delts', 'secondary', 0.50),
  ('dumbbell-bench-press', 'triceps', 'secondary', 0.40),
  ('incline-dumbbell-press', 'chest', 'primary', 0.90),
  ('incline-dumbbell-press', 'front_delts', 'secondary', 0.60),
  ('incline-dumbbell-press', 'triceps', 'secondary', 0.40),
  ('decline-dumbbell-press', 'chest', 'primary', 0.90),
  ('decline-dumbbell-press', 'triceps', 'secondary', 0.40),
  ('dumbbell-fly', 'chest', 'primary', 1.00),
  ('dumbbell-fly', 'front_delts', 'secondary', 0.30),
  ('incline-dumbbell-fly', 'chest', 'primary', 0.90),
  ('incline-dumbbell-fly', 'front_delts', 'secondary', 0.40),
  ('cable-fly', 'chest', 'primary', 1.00),
  ('cable-fly', 'front_delts', 'secondary', 0.30),
  ('cable-crossover', 'chest', 'primary', 1.00),
  ('cable-crossover', 'front_delts', 'secondary', 0.30),
  ('machine-chest-press', 'chest', 'primary', 1.00),
  ('machine-chest-press', 'triceps', 'secondary', 0.40),
  ('machine-chest-press', 'front_delts', 'secondary', 0.40),
  ('pec-deck', 'chest', 'primary', 1.00),
  ('push-up', 'chest', 'primary', 0.90),
  ('push-up', 'triceps', 'secondary', 0.50),
  ('push-up', 'front_delts', 'secondary', 0.40),
  ('push-up', 'abs', 'secondary', 0.30),
  ('chest-dip', 'chest', 'primary', 0.90),
  ('chest-dip', 'triceps', 'secondary', 0.60),
  ('chest-dip', 'front_delts', 'secondary', 0.40),
  ('deadlift', 'lower_back', 'primary', 0.90),
  ('deadlift', 'glutes', 'primary', 0.90),
  ('deadlift', 'hamstrings', 'primary', 0.90),
  ('deadlift', 'traps', 'secondary', 0.50),
  ('deadlift', 'lats', 'secondary', 0.40),
  ('deadlift', 'forearms', 'secondary', 0.40),
  ('deadlift', 'quads', 'secondary', 0.40),
  ('sumo-deadlift', 'glutes', 'primary', 0.90),
  ('sumo-deadlift', 'quads', 'primary', 0.70),
  ('sumo-deadlift', 'hamstrings', 'secondary', 0.60),
  ('sumo-deadlift', 'lower_back', 'secondary', 0.60),
  ('sumo-deadlift', 'adductors', 'secondary', 0.50),
  ('sumo-deadlift', 'traps', 'secondary', 0.40),
  ('rack-pull', 'lower_back', 'primary', 0.80),
  ('rack-pull', 'traps', 'primary', 0.70),
  ('rack-pull', 'glutes', 'secondary', 0.60),
  ('rack-pull', 'lats', 'secondary', 0.40),
  ('rack-pull', 'forearms', 'secondary', 0.40),
  ('barbell-row', 'lats', 'primary', 0.90),
  ('barbell-row', 'rhomboids', 'primary', 0.70),
  ('barbell-row', 'traps', 'secondary', 0.50),
  ('barbell-row', 'rear_delts', 'secondary', 0.50),
  ('barbell-row', 'biceps', 'secondary', 0.40),
  ('barbell-row', 'lower_back', 'secondary', 0.40),
  ('pendlay-row', 'lats', 'primary', 0.90),
  ('pendlay-row', 'rhomboids', 'primary', 0.70),
  ('pendlay-row', 'traps', 'secondary', 0.50),
  ('pendlay-row', 'rear_delts', 'secondary', 0.40),
  ('pendlay-row', 'biceps', 'secondary', 0.40),
  ('dumbbell-row', 'lats', 'primary', 1.00),
  ('dumbbell-row', 'rhomboids', 'secondary', 0.60),
  ('dumbbell-row', 'rear_delts', 'secondary', 0.40),
  ('dumbbell-row', 'biceps', 'secondary', 0.40),
  ('t-bar-row', 'lats', 'primary', 0.90),
  ('t-bar-row', 'rhomboids', 'primary', 0.70),
  ('t-bar-row', 'traps', 'secondary', 0.50),
  ('t-bar-row', 'biceps', 'secondary', 0.40),
  ('chest-supported-row', 'rhomboids', 'primary', 0.90),
  ('chest-supported-row', 'lats', 'primary', 0.80),
  ('chest-supported-row', 'rear_delts', 'secondary', 0.50),
  ('chest-supported-row', 'biceps', 'secondary', 0.40),
  ('seated-cable-row', 'lats', 'primary', 0.90),
  ('seated-cable-row', 'rhomboids', 'primary', 0.70),
  ('seated-cable-row', 'biceps', 'secondary', 0.40),
  ('seated-cable-row', 'rear_delts', 'secondary', 0.40),
  ('machine-row', 'lats', 'primary', 0.90),
  ('machine-row', 'rhomboids', 'secondary', 0.60),
  ('machine-row', 'biceps', 'secondary', 0.40),
  ('lat-pulldown', 'lats', 'primary', 1.00),
  ('lat-pulldown', 'biceps', 'secondary', 0.50),
  ('lat-pulldown', 'rhomboids', 'secondary', 0.40),
  ('close-grip-lat-pulldown', 'lats', 'primary', 1.00),
  ('close-grip-lat-pulldown', 'biceps', 'secondary', 0.50),
  ('pull-up', 'lats', 'primary', 1.00),
  ('pull-up', 'biceps', 'secondary', 0.50),
  ('pull-up', 'rhomboids', 'secondary', 0.40),
  ('pull-up', 'abs', 'secondary', 0.30),
  ('chin-up', 'lats', 'primary', 0.90),
  ('chin-up', 'biceps', 'primary', 0.70),
  ('chin-up', 'abs', 'secondary', 0.30),
  ('straight-arm-pulldown', 'lats', 'primary', 1.00),
  ('straight-arm-pulldown', 'triceps', 'secondary', 0.30),
  ('barbell-shrug', 'traps', 'primary', 1.00),
  ('barbell-shrug', 'forearms', 'secondary', 0.40),
  ('dumbbell-shrug', 'traps', 'primary', 1.00),
  ('dumbbell-shrug', 'forearms', 'secondary', 0.40),
  ('face-pull', 'rear_delts', 'primary', 1.00),
  ('face-pull', 'rhomboids', 'secondary', 0.60),
  ('face-pull', 'traps', 'secondary', 0.40),
  ('back-extension', 'lower_back', 'primary', 1.00),
  ('back-extension', 'glutes', 'secondary', 0.60),
  ('back-extension', 'hamstrings', 'secondary', 0.50),
  ('overhead-press', 'front_delts', 'primary', 1.00),
  ('overhead-press', 'side_delts', 'secondary', 0.50),
  ('overhead-press', 'triceps', 'secondary', 0.50),
  ('overhead-press', 'abs', 'secondary', 0.30),
  ('seated-dumbbell-shoulder-press', 'front_delts', 'primary', 1.00),
  ('seated-dumbbell-shoulder-press', 'side_delts', 'secondary', 0.50),
  ('seated-dumbbell-shoulder-press', 'triceps', 'secondary', 0.40),
  ('arnold-press', 'front_delts', 'primary', 1.00),
  ('arnold-press', 'side_delts', 'secondary', 0.60),
  ('arnold-press', 'triceps', 'secondary', 0.40),
  ('machine-shoulder-press', 'front_delts', 'primary', 1.00),
  ('machine-shoulder-press', 'side_delts', 'secondary', 0.40),
  ('machine-shoulder-press', 'triceps', 'secondary', 0.40),
  ('push-press', 'front_delts', 'primary', 0.90),
  ('push-press', 'triceps', 'secondary', 0.50),
  ('push-press', 'quads', 'secondary', 0.40),
  ('push-press', 'abs', 'secondary', 0.30),
  ('lateral-raise', 'side_delts', 'primary', 1.00),
  ('lateral-raise', 'traps', 'secondary', 0.30),
  ('cable-lateral-raise', 'side_delts', 'primary', 1.00),
  ('front-raise', 'front_delts', 'primary', 1.00),
  ('rear-delt-fly', 'rear_delts', 'primary', 1.00),
  ('rear-delt-fly', 'rhomboids', 'secondary', 0.50),
  ('reverse-pec-deck', 'rear_delts', 'primary', 1.00),
  ('reverse-pec-deck', 'rhomboids', 'secondary', 0.50),
  ('upright-row', 'side_delts', 'primary', 0.90),
  ('upright-row', 'traps', 'primary', 0.70),
  ('upright-row', 'biceps', 'secondary', 0.30),
  ('barbell-curl', 'biceps', 'primary', 1.00),
  ('barbell-curl', 'forearms', 'secondary', 0.40),
  ('ez-bar-curl', 'biceps', 'primary', 1.00),
  ('ez-bar-curl', 'forearms', 'secondary', 0.40),
  ('dumbbell-curl', 'biceps', 'primary', 1.00),
  ('dumbbell-curl', 'forearms', 'secondary', 0.40),
  ('hammer-curl', 'biceps', 'primary', 0.90),
  ('hammer-curl', 'forearms', 'primary', 0.70),
  ('incline-dumbbell-curl', 'biceps', 'primary', 1.00),
  ('incline-dumbbell-curl', 'forearms', 'secondary', 0.30),
  ('preacher-curl', 'biceps', 'primary', 1.00),
  ('preacher-curl', 'forearms', 'secondary', 0.30),
  ('concentration-curl', 'biceps', 'primary', 1.00),
  ('cable-curl', 'biceps', 'primary', 1.00),
  ('cable-curl', 'forearms', 'secondary', 0.30),
  ('spider-curl', 'biceps', 'primary', 1.00),
  ('close-grip-bench-press', 'triceps', 'primary', 1.00),
  ('close-grip-bench-press', 'chest', 'secondary', 0.60),
  ('close-grip-bench-press', 'front_delts', 'secondary', 0.40),
  ('skullcrusher', 'triceps', 'primary', 1.00),
  ('overhead-tricep-extension', 'triceps', 'primary', 1.00),
  ('tricep-pushdown', 'triceps', 'primary', 1.00),
  ('rope-pushdown', 'triceps', 'primary', 1.00),
  ('tricep-kickback', 'triceps', 'primary', 1.00),
  ('bench-dip', 'triceps', 'primary', 1.00),
  ('bench-dip', 'chest', 'secondary', 0.40),
  ('bench-dip', 'front_delts', 'secondary', 0.30),
  ('tricep-dip', 'triceps', 'primary', 1.00),
  ('tricep-dip', 'chest', 'secondary', 0.50),
  ('diamond-push-up', 'triceps', 'primary', 0.90),
  ('diamond-push-up', 'chest', 'secondary', 0.60),
  ('wrist-curl', 'forearms', 'primary', 1.00),
  ('reverse-wrist-curl', 'forearms', 'primary', 1.00),
  ('farmers-walk', 'forearms', 'primary', 1.00),
  ('farmers-walk', 'traps', 'secondary', 0.60),
  ('farmers-walk', 'abs', 'secondary', 0.40),
  ('farmers-walk', 'glutes', 'secondary', 0.30),
  ('reverse-curl', 'forearms', 'primary', 0.90),
  ('reverse-curl', 'biceps', 'secondary', 0.60),
  ('back-squat', 'quads', 'primary', 1.00),
  ('back-squat', 'glutes', 'primary', 0.80),
  ('back-squat', 'hamstrings', 'secondary', 0.50),
  ('back-squat', 'lower_back', 'secondary', 0.40),
  ('back-squat', 'abs', 'secondary', 0.40),
  ('back-squat', 'adductors', 'secondary', 0.40),
  ('front-squat', 'quads', 'primary', 1.00),
  ('front-squat', 'glutes', 'secondary', 0.60),
  ('front-squat', 'abs', 'secondary', 0.50),
  ('front-squat', 'lower_back', 'secondary', 0.40),
  ('goblet-squat', 'quads', 'primary', 0.90),
  ('goblet-squat', 'glutes', 'secondary', 0.60),
  ('goblet-squat', 'abs', 'secondary', 0.40),
  ('hack-squat', 'quads', 'primary', 1.00),
  ('hack-squat', 'glutes', 'secondary', 0.50),
  ('leg-press', 'quads', 'primary', 1.00),
  ('leg-press', 'glutes', 'secondary', 0.60),
  ('leg-press', 'hamstrings', 'secondary', 0.40),
  ('bulgarian-split-squat', 'quads', 'primary', 0.90),
  ('bulgarian-split-squat', 'glutes', 'primary', 0.90),
  ('bulgarian-split-squat', 'hamstrings', 'secondary', 0.40),
  ('bulgarian-split-squat', 'adductors', 'secondary', 0.30),
  ('walking-lunge', 'quads', 'primary', 0.90),
  ('walking-lunge', 'glutes', 'primary', 0.80),
  ('walking-lunge', 'hamstrings', 'secondary', 0.40),
  ('reverse-lunge', 'glutes', 'primary', 0.90),
  ('reverse-lunge', 'quads', 'primary', 0.70),
  ('reverse-lunge', 'hamstrings', 'secondary', 0.40),
  ('step-up', 'quads', 'primary', 0.90),
  ('step-up', 'glutes', 'primary', 0.80),
  ('romanian-deadlift', 'hamstrings', 'primary', 1.00),
  ('romanian-deadlift', 'glutes', 'primary', 0.80),
  ('romanian-deadlift', 'lower_back', 'secondary', 0.60),
  ('romanian-deadlift', 'forearms', 'secondary', 0.30),
  ('stiff-leg-deadlift', 'hamstrings', 'primary', 1.00),
  ('stiff-leg-deadlift', 'glutes', 'primary', 0.70),
  ('stiff-leg-deadlift', 'lower_back', 'secondary', 0.60),
  ('good-morning', 'hamstrings', 'primary', 0.90),
  ('good-morning', 'lower_back', 'primary', 0.80),
  ('good-morning', 'glutes', 'secondary', 0.60),
  ('leg-extension', 'quads', 'primary', 1.00),
  ('lying-leg-curl', 'hamstrings', 'primary', 1.00),
  ('lying-leg-curl', 'calves', 'secondary', 0.30),
  ('seated-leg-curl', 'hamstrings', 'primary', 1.00),
  ('nordic-curl', 'hamstrings', 'primary', 1.00),
  ('nordic-curl', 'glutes', 'secondary', 0.40),
  ('hip-thrust', 'glutes', 'primary', 1.00),
  ('hip-thrust', 'hamstrings', 'secondary', 0.50),
  ('glute-bridge', 'glutes', 'primary', 1.00),
  ('glute-bridge', 'hamstrings', 'secondary', 0.40),
  ('cable-kickback', 'glutes', 'primary', 1.00),
  ('standing-calf-raise', 'calves', 'primary', 1.00),
  ('seated-calf-raise', 'calves', 'primary', 1.00),
  ('adductor-machine', 'adductors', 'primary', 1.00),
  ('abductor-machine', 'glutes', 'primary', 0.90),
  ('plank', 'abs', 'primary', 1.00),
  ('plank', 'obliques', 'secondary', 0.50),
  ('plank', 'lower_back', 'secondary', 0.30),
  ('side-plank', 'obliques', 'primary', 1.00),
  ('side-plank', 'abs', 'secondary', 0.50),
  ('hanging-leg-raise', 'abs', 'primary', 1.00),
  ('hanging-leg-raise', 'obliques', 'secondary', 0.40),
  ('hanging-leg-raise', 'forearms', 'secondary', 0.30),
  ('hanging-knee-raise', 'abs', 'primary', 1.00),
  ('hanging-knee-raise', 'forearms', 'secondary', 0.30),
  ('cable-crunch', 'abs', 'primary', 1.00),
  ('cable-crunch', 'obliques', 'secondary', 0.30),
  ('crunch', 'abs', 'primary', 1.00),
  ('sit-up', 'abs', 'primary', 1.00),
  ('sit-up', 'obliques', 'secondary', 0.30),
  ('russian-twist', 'obliques', 'primary', 1.00),
  ('russian-twist', 'abs', 'secondary', 0.60),
  ('ab-wheel-rollout', 'abs', 'primary', 1.00),
  ('ab-wheel-rollout', 'lats', 'secondary', 0.40),
  ('ab-wheel-rollout', 'lower_back', 'secondary', 0.30),
  ('dead-bug', 'abs', 'primary', 1.00),
  ('mountain-climber', 'abs', 'primary', 0.90),
  ('mountain-climber', 'obliques', 'secondary', 0.50),
  ('mountain-climber', 'front_delts', 'secondary', 0.30),
  ('pallof-press', 'obliques', 'primary', 1.00),
  ('pallof-press', 'abs', 'secondary', 0.60),
  ('treadmill-run', 'quads', 'secondary', 0.60),
  ('treadmill-run', 'calves', 'secondary', 0.60),
  ('treadmill-run', 'hamstrings', 'secondary', 0.50),
  ('treadmill-run', 'glutes', 'secondary', 0.40),
  ('stationary-bike', 'quads', 'primary', 0.70),
  ('stationary-bike', 'glutes', 'secondary', 0.40),
  ('stationary-bike', 'calves', 'secondary', 0.30),
  ('rowing-machine', 'lats', 'secondary', 0.60),
  ('rowing-machine', 'quads', 'secondary', 0.50),
  ('rowing-machine', 'rhomboids', 'secondary', 0.40),
  ('rowing-machine', 'biceps', 'secondary', 0.30),
  ('elliptical', 'quads', 'secondary', 0.50),
  ('elliptical', 'glutes', 'secondary', 0.40),
  ('elliptical', 'calves', 'secondary', 0.30),
  ('stair-climber', 'glutes', 'primary', 0.70),
  ('stair-climber', 'quads', 'secondary', 0.60),
  ('stair-climber', 'calves', 'secondary', 0.40),
  ('jump-rope', 'calves', 'primary', 0.80),
  ('jump-rope', 'quads', 'secondary', 0.40),
  ('arm-circles', 'front_delts', 'secondary', 0.40),
  ('arm-circles', 'side_delts', 'secondary', 0.40),
  ('arm-circles', 'rear_delts', 'secondary', 0.30),
  ('band-pass-through', 'front_delts', 'secondary', 0.40),
  ('band-pass-through', 'rear_delts', 'secondary', 0.40),
  ('band-pass-through', 'traps', 'secondary', 0.30),
  ('scapular-wall-slide', 'rhomboids', 'secondary', 0.50),
  ('scapular-wall-slide', 'traps', 'secondary', 0.40),
  ('scapular-wall-slide', 'rear_delts', 'secondary', 0.30),
  ('cat-cow', 'lower_back', 'secondary', 0.40),
  ('cat-cow', 'abs', 'secondary', 0.30),
  ('worlds-greatest-stretch', 'adductors', 'secondary', 0.40),
  ('worlds-greatest-stretch', 'glutes', 'secondary', 0.40),
  ('worlds-greatest-stretch', 'obliques', 'secondary', 0.30),
  ('hip-flexor-stretch', 'quads', 'secondary', 0.30),
  ('hip-flexor-stretch', 'glutes', 'secondary', 0.30),
  ('thoracic-rotation', 'obliques', 'secondary', 0.40),
  ('thoracic-rotation', 'lower_back', 'secondary', 0.30),
  ('leg-swing', 'hamstrings', 'secondary', 0.30),
  ('leg-swing', 'glutes', 'secondary', 0.30),
  ('leg-swing', 'adductors', 'secondary', 0.30)
) as v(slug, muscle_group_id, role, activation)
join hadid.exercises e on e.slug = v.slug
on conflict (exercise_id, muscle_group_id) do update set
  role = excluded.role, activation = excluded.activation;

-- Badge definitions
insert into hadid.achievements (id, category, name, description, icon, metric, threshold, sort_order) values
  ('first_rep', 'milestones', 'First Rep', 'Finish your first workout.', '🎯', 'workouts_count', 1, 1),
  ('getting_serious', 'milestones', 'Getting Serious', 'Finish 5 workouts.', '💪', 'workouts_count', 5, 2),
  ('gym_regular', 'milestones', 'Gym Regular', 'Finish 25 workouts.', '🏋️', 'workouts_count', 25, 3),
  ('century_club', 'milestones', 'Century Club', 'Finish 100 workouts.', '💯', 'workouts_count', 100, 4),
  ('iron_veteran', 'milestones', 'Iron Veteran', 'Finish 250 workouts.', '🎖️', 'workouts_count', 250, 5),
  ('week_warrior', 'milestones', 'Week Warrior', 'Train 7 days in a row.', '🔥', 'streak_days', 7, 6),
  ('month_strong', 'milestones', 'Month Strong', 'Hold a 30-day streak.', '📅', 'streak_days', 30, 7),
  ('unbreakable', 'milestones', 'Unbreakable', 'Hold a 100-day streak.', '⛰️', 'streak_days', 100, 8),
  ('set_stacker', 'volume', 'Set Stacker', 'Log 100 working sets.', '📚', 'sets_count', 100, 1),
  ('set_legend', 'volume', 'Set Legend', 'Log 500 working sets.', '🗂️', 'sets_count', 500, 2),
  ('rep_machine', 'volume', 'Rep Machine', 'Log 2,000 working sets.', '⚙️', 'sets_count', 2000, 3),
  ('set_immortal', 'volume', 'Set Immortal', 'Log 5,000 working sets.', '♾️', 'sets_count', 5000, 4),
  ('volume_machine', 'volume', 'Volume Machine', 'Move 10,000 kg in total.', '📦', 'total_volume_kg', 10000, 5),
  ('ton_lifter', 'volume', 'Ton Lifter', 'Move 50,000 kg in total.', '🏗️', 'total_volume_kg', 50000, 6),
  ('heavy_hauler', 'volume', 'Heavy Hauler', 'Move 250,000 kg in total.', '🚛', 'total_volume_kg', 250000, 7),
  ('mountain_mover', 'volume', 'Mountain Mover', 'Move 1,000,000 kg in total.', '🏔️', 'total_volume_kg', 1000000, 8),
  ('record_breaker', 'strength', 'Record Breaker', 'Set your first personal record.', '🥇', 'pr_count', 1, 1),
  ('pr_hunter', 'strength', 'PR Hunter', 'Set 5 personal records.', '🏹', 'pr_count', 5, 2),
  ('record_machine', 'strength', 'Record Machine', 'Set 15 personal records.', '🤖', 'pr_count', 15, 3),
  ('pr_collector', 'strength', 'PR Collector', 'Set 30 personal records.', '🗃️', 'pr_count', 30, 4),
  ('relentless', 'strength', 'Relentless', 'Set 60 personal records.', '⚡', 'pr_count', 60, 5),
  ('pr_addict', 'strength', 'PR Addict', 'Set 100 personal records.', '🎰', 'pr_count', 100, 6),
  ('iron_will', 'strength', 'Iron Will', 'Set 200 personal records.', '🛡️', 'pr_count', 200, 7),
  ('immortal', 'strength', 'Immortal', 'Set 500 personal records.', '👑', 'pr_count', 500, 8)
on conflict (id) do update set
  category = excluded.category, name = excluded.name,
  description = excluded.description, icon = excluded.icon,
  metric = excluded.metric, threshold = excluded.threshold,
  sort_order = excluded.sort_order;

commit;
